### ISSUE TITLE
text/plain treated as json

### ISSUE THREAD

**Issue by dagardner-nv** [testinggospels/camouflage#223]
**Describe the bug**
Setting `Content-Type: text/plain` causes the response to be treated as if it were JSON.

**To Reproduce**
1. Mock File Content 
GET.mock:
```
HTTP/1.1 200 OK
Content-Type: text/plain

line1
line2
line3
```

POST.mock
```
HTTP/1.1 200 OK
Content-Type: text/plain

OK
```
2. Folder Structure 
```
mocks/plain-text/
mocks/plain-text/POST.mock
mocks/plain-text/GET.mock
```
4. Error Stack Trace
```
curl -v "http://localhost:8080/plain-text" 
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /plain-text HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/plain; charset=utf-8
< Content-Length: 15
< ETag: W/"f-MjRrWBZ2yhk5qhlHiP21s/LGDjo"
< Vary: Accept-Encoding
< Date: Thu, 27 Jul 2023 19:24:44 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host localhost left intact
line1line2line3
```
Camouflage then logs:
```
2023-07-27 12:24:44 warn: Unexpected token l in JSON at position 0 
```

**Expected behavior**
Camouflage shouldn't attempt to parse output as JSON when content-type is `text/plain`.
New line characters should not be stripped from output.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Debian 11.7
 - Browser curl
 - Version 8.1.2

**Additional context**
[camouflage.log](https://github.com/testinggospels/camouflage/files/12187579/camouflage.log)

**Comment by dagardner-nv** [comment]
I am able to work-around the issue using the `file` helper.

**Comment by shubhendumadhukar** [comment]
@dagardner-nv 

>warn: Unexpected token l in JSON at position 0 

Is a warning message that Camouflage throws since it expects responses to be json by default, however it doesn't affect your responses and the message can be ignored.

New lines being stripped out is a bug since we split the mock file contents with new line.
https://github.com/testinggospels/camouflage/blob/98dcc2c2edc709a40a6cf9437adfe9ae498ce293/src/parser/HttpParser.ts#L142

and then join them without the new line
https://github.com/testinggospels/camouflage/blob/98dcc2c2edc709a40a6cf9437adfe9ae498ce293/src/parser/HttpParser.ts#L172

which should not be the case. I will provide a fix.
